"""Layer 1C detector APIs."""

from trinetra.detectors.near_duplicate import (
    DEFAULT_SIMILARITY_THRESHOLD,
    DuplicateCluster,
    DuplicateMember,
    DuplicatePair,
    EmbeddingSpaceMismatchError,
    InvalidFeatureBatchError,
    NearDuplicateDetector,
    NearDuplicateError,
    NearDuplicateResult,
    cosine_similarity,
)
from trinetra.detectors.label_manipulation import (
    ContributorSourceMetadata,
    DatasetFeatureMismatchError,
    DEFAULT_DISAGREEMENT_THRESHOLD,
    DEFAULT_MIN_SAME_CLASS_NEIGHBORS,
    DEFAULT_NEIGHBOR_COUNT,
    ExcludedImage,
    LabelManipulationConfiguration,
    LabelManipulationDetector,
    LabelManipulationError,
    LabelManipulationFinding,
    LabelManipulationResult,
    LabelReference,
    LABEL_MANIPULATION_DETECTOR_NAME,
    LABEL_MANIPULATION_DETECTOR_VERSION,
    LABEL_MANIPULATION_SCHEMA_VERSION,
    MissingEmbeddingError,
    NeighborClassCount,
    NeighborEvidence,
)

__all__ = [
    "DEFAULT_SIMILARITY_THRESHOLD",
    "DuplicateCluster",
    "DuplicateMember",
    "DuplicatePair",
    "EmbeddingSpaceMismatchError",
    "InvalidFeatureBatchError",
    "NearDuplicateDetector",
    "NearDuplicateError",
    "NearDuplicateResult",
    "cosine_similarity",
    "ContributorSourceMetadata",
    "DatasetFeatureMismatchError",
    "DEFAULT_DISAGREEMENT_THRESHOLD",
    "DEFAULT_MIN_SAME_CLASS_NEIGHBORS",
    "DEFAULT_NEIGHBOR_COUNT",
    "ExcludedImage",
    "LabelManipulationConfiguration",
    "LabelManipulationDetector",
    "LabelManipulationError",
    "LabelManipulationFinding",
    "LabelManipulationResult",
    "LabelReference",
    "LABEL_MANIPULATION_DETECTOR_NAME",
    "LABEL_MANIPULATION_DETECTOR_VERSION",
    "LABEL_MANIPULATION_SCHEMA_VERSION",
    "MissingEmbeddingError",
    "NeighborClassCount",
    "NeighborEvidence",
]
