"""Layer 1F provenance-aware detector evidence aggregation."""

from trinetra.contributor.aggregation import (
    AggregatedEvidence,
    AggregationConfiguration,
    AggregationError,
    AggregationWeights,
    CONTRIBUTOR_RISK_DETECTOR_NAME,
    CONTRIBUTOR_RISK_DETECTOR_VERSION,
    CONTRIBUTOR_RISK_SCHEMA_VERSION,
    ContributorRiskAggregator,
    ContributorRiskSummary,
    DetectorCategory,
    DetectorEvidenceConflict,
    DetectorEvidenceCounts,
    InvalidDetectorEvidenceError,
    ProvenanceGroupSummary,
    Recommendation,
    UnattributedSummary,
    UnknownDetectorError,
)
from trinetra.contributor.provenance import (
    InvalidProvenanceError,
    ProvenanceConflict,
    ProvenanceMetadata,
    ProvenanceValue,
)

__all__ = [
    "AggregatedEvidence",
    "AggregationConfiguration",
    "AggregationError",
    "AggregationWeights",
    "CONTRIBUTOR_RISK_DETECTOR_NAME",
    "CONTRIBUTOR_RISK_DETECTOR_VERSION",
    "CONTRIBUTOR_RISK_SCHEMA_VERSION",
    "ContributorRiskAggregator",
    "ContributorRiskSummary",
    "DetectorCategory",
    "DetectorEvidenceConflict",
    "DetectorEvidenceCounts",
    "InvalidDetectorEvidenceError",
    "InvalidProvenanceError",
    "ProvenanceConflict",
    "ProvenanceGroupSummary",
    "ProvenanceMetadata",
    "ProvenanceValue",
    "Recommendation",
    "UnattributedSummary",
    "UnknownDetectorError",
]
